module.exports = {
    "North America": {
        "Aruba": "aruba.json",
        "Anguilla": "anguilla.json",
        "Antigua and Barb.": "antiguaandbarb.json",
        "Bahamas": "bahamas.json",
        "Bajo Nuevo Bank (Petrel Is.)": "bajonuevobankpetrelis.json",
        "St-Barthélemy": "stbarthlemy.json",
        "Belize": "belize.json",
        "Bermuda": "bermuda.json",
        "Barbados": "barbados.json",
        "Canada": "canada.json",
        "Costa Rica": "costarica.json",
        "Cuba": "cuba.json",
        "Curaçao": "curaao.json",
        "Cayman Is.": "caymanis.json",
        "Dominica": "dominica.json",
        "Dominican Rep.": "dominicanrep.json",
        "Grenada": "grenada.json",
        "Greenland": "greenland.json",
        "Guatemala": "guatemala.json",
        "Honduras": "honduras.json",
        "Haiti": "haiti.json",
        "Jamaica": "jamaica.json",
        "St. Kitts and Nevis": "stkittsandnevis.json",
        "Saint Lucia": "saintlucia.json",
        "St-Martin": "stmartin.json",
        "Mexico": "mexico.json",
        "Montserrat": "montserrat.json",
        "Nicaragua": "nicaragua.json",
        "Panama": "panama.json",
        "Puerto Rico": "puertorico.json",
        "Serranilla Bank": "serranillabank.json",
        "El Salvador": "elsalvador.json",
        "St. Pierre and Miquelon": "stpierreandmiquelon.json",
        "Sint Maarten": "sintmaarten.json",
        "Turks and Caicos Is.": "turksandcaicosis.json",
        "Trinidad and Tobago": "trinidadandtobago.json",
        "U.S. Minor Outlying Is.": "usminoroutlyingis.json",
        "United States": "unitedstates.json",
        "USNB Guantanamo Bay": "usnbguantanamobay.json",
        "St. Vin. and Gren.": "stvinandgren.json",
        "British Virgin Is.": "britishvirginis.json",
        "U.S. Virgin Is.": "usvirginis.json"
    },
    "Asia": {
        "Afghanistan": "afghanistan.json",
        "United Arab Emirates": "unitedarabemirates.json",
        "Armenia": "armenia.json",
        "Azerbaijan": "azerbaijan.json",
        "Bangladesh": "bangladesh.json",
        "Bahrain": "bahrain.json",
        "Brunei": "brunei.json",
        "Bhutan": "bhutan.json",
        "China": "china.json",
        "Cyprus U.N. Buffer Zone": "cyprusunbufferzone.json",
        "N. Cyprus": "ncyprus.json",
        "Cyprus": "cyprus.json",
        "Dhekelia": "dhekelia.json",
        "Georgia": "georgia.json",
        "Hong Kong": "hongkong.json",
        "Indonesia": "indonesia.json",
        "India": "india.json",
        "Indian Ocean Ter.": "indianoceanter.json",
        "Iran": "iran.json",
        "Iraq": "iraq.json",
        "Israel": "israel.json",
        "Jordan": "jordan.json",
        "Japan": "japan.json",
        "Baikonur": "baikonur.json",
        "Siachen Glacier": "siachenglacier.json",
        "Kazakhstan": "kazakhstan.json",
        "Kyrgyzstan": "kyrgyzstan.json",
        "Cambodia": "cambodia.json",
        "Korea": "korea.json",
        "Kuwait": "kuwait.json",
        "Lao PDR": "laopdr.json",
        "Lebanon": "lebanon.json",
        "Sri Lanka": "srilanka.json",
        "Macao": "macao.json",
        "Myanmar": "myanmar.json",
        "Mongolia": "mongolia.json",
        "Malaysia": "malaysia.json",
        "Nepal": "nepal.json",
        "Oman": "oman.json",
        "Pakistan": "pakistan.json",
        "Spratly Is.": "spratlyis.json",
        "Philippines": "philippines.json",
        "Dem. Rep. Korea": "demrepkorea.json",
        "Palestine": "palestine.json",
        "Qatar": "qatar.json",
        "Saudi Arabia": "saudiarabia.json",
        "Scarborough Reef": "scarboroughreef.json",
        "Singapore": "singapore.json",
        "Syria": "syria.json",
        "Thailand": "thailand.json",
        "Tajikistan": "tajikistan.json",
        "Turkmenistan": "turkmenistan.json",
        "Timor-Leste": "timorleste.json",
        "Turkey": "turkey.json",
        "Taiwan": "taiwan.json",
        "Uzbekistan": "uzbekistan.json",
        "Vietnam": "vietnam.json",
        "Akrotiri": "akrotiri.json",
        "Yemen": "yemen.json"
    },
    "Africa": {
        "Angola": "angola.json",
        "Burundi": "burundi.json",
        "Benin": "benin.json",
        "Burkina Faso": "burkinafaso.json",
        "Botswana": "botswana.json",
        "Central African Rep.": "centralafricanrep.json",
        "Côte d'Ivoire": "ctedivoire.json",
        "Cameroon": "cameroon.json",
        "Dem. Rep. Congo": "demrepcongo.json",
        "Congo": "congo.json",
        "Comoros": "comoros.json",
        "Cape Verde": "capeverde.json",
        "Djibouti": "djibouti.json",
        "Algeria": "algeria.json",
        "Egypt": "egypt.json",
        "Eritrea": "eritrea.json",
        "Ethiopia": "ethiopia.json",
        "Gabon": "gabon.json",
        "Ghana": "ghana.json",
        "Guinea": "guinea.json",
        "Gambia": "gambia.json",
        "Guinea-Bissau": "guineabissau.json",
        "Eq. Guinea": "eqguinea.json",
        "Kenya": "kenya.json",
        "Liberia": "liberia.json",
        "Libya": "libya.json",
        "Lesotho": "lesotho.json",
        "Morocco": "morocco.json",
        "Madagascar": "madagascar.json",
        "Mali": "mali.json",
        "Mozambique": "mozambique.json",
        "Mauritania": "mauritania.json",
        "Malawi": "malawi.json",
        "Namibia": "namibia.json",
        "Niger": "niger.json",
        "Nigeria": "nigeria.json",
        "Rwanda": "rwanda.json",
        "W. Sahara": "wsahara.json",
        "Sudan": "sudan.json",
        "S. Sudan": "ssudan.json",
        "Senegal": "senegal.json",
        "Sierra Leone": "sierraleone.json",
        "Somaliland": "somaliland.json",
        "Somalia": "somalia.json",
        "São Tomé and Principe": "sotomandprincipe.json",
        "Swaziland": "swaziland.json",
        "Chad": "chad.json",
        "Togo": "togo.json",
        "Tunisia": "tunisia.json",
        "Tanzania": "tanzania.json",
        "Uganda": "uganda.json",
        "South Africa": "southafrica.json",
        "Zambia": "zambia.json",
        "Zimbabwe": "zimbabwe.json"
    },
    "Europe": {
        "Albania": "albania.json",
        "Aland": "aland.json",
        "Andorra": "andorra.json",
        "Austria": "austria.json",
        "Belgium": "belgium.json",
        "Bulgaria": "bulgaria.json",
        "Bosnia and Herz.": "bosniaandherz.json",
        "Belarus": "belarus.json",
        "Switzerland": "switzerland.json",
        "Czech Rep.": "czechrep.json",
        "Germany": "germany.json",
        "Denmark": "denmark.json",
        "Spain": "spain.json",
        "Estonia": "estonia.json",
        "Finland": "finland.json",
        "France": "france.json",
        "Faeroe Is.": "faeroeis.json",
        "United Kingdom": "unitedkingdom.json",
        "Guernsey": "guernsey.json",
        "Gibraltar": "gibraltar.json",
        "Greece": "greece.json",
        "Croatia": "croatia.json",
        "Hungary": "hungary.json",
        "Isle of Man": "isleofman.json",
        "Ireland": "ireland.json",
        "Iceland": "iceland.json",
        "Italy": "italy.json",
        "Jersey": "jersey.json",
        "Kosovo": "kosovo.json",
        "Liechtenstein": "liechtenstein.json",
        "Lithuania": "lithuania.json",
        "Luxembourg": "luxembourg.json",
        "Latvia": "latvia.json",
        "Monaco": "monaco.json",
        "Moldova": "moldova.json",
        "Macedonia": "macedonia.json",
        "Malta": "malta.json",
        "Montenegro": "montenegro.json",
        "Netherlands": "netherlands.json",
        "Norway": "norway.json",
        "Poland": "poland.json",
        "Portugal": "portugal.json",
        "Romania": "romania.json",
        "Russia": "russia.json",
        "San Marino": "sanmarino.json",
        "Serbia": "serbia.json",
        "Slovakia": "slovakia.json",
        "Slovenia": "slovenia.json",
        "Sweden": "sweden.json",
        "Ukraine": "ukraine.json",
        "Vatican": "vatican.json"
    },
    "South America": {
        "Argentina": "argentina.json",
        "Bolivia": "bolivia.json",
        "Brazil": "brazil.json",
        "Chile": "chile.json",
        "Colombia": "colombia.json",
        "Ecuador": "ecuador.json",
        "Falkland Is.": "falklandis.json",
        "Guyana": "guyana.json",
        "Peru": "peru.json",
        "Paraguay": "paraguay.json",
        "Suriname": "suriname.json",
        "Uruguay": "uruguay.json",
        "Venezuela": "venezuela.json"
    },
    "Oceania": {
        "American Samoa": "americansamoa.json",
        "Ashmore and Cartier Is.": "ashmoreandcartieris.json",
        "Australia": "australia.json",
        "Cook Is.": "cookis.json",
        "Coral Sea Is.": "coralseais.json",
        "Fiji": "fiji.json",
        "Micronesia": "micronesia.json",
        "Guam": "guam.json",
        "Kiribati": "kiribati.json",
        "Marshall Is.": "marshallis.json",
        "N. Mariana Is.": "nmarianais.json",
        "New Caledonia": "newcaledonia.json",
        "Norfolk Island": "norfolkisland.json",
        "Niue": "niue.json",
        "Nauru": "nauru.json",
        "New Zealand": "newzealand.json",
        "Pitcairn Is.": "pitcairnis.json",
        "Palau": "palau.json",
        "Papua New Guinea": "papuanewguinea.json",
        "Fr. Polynesia": "frpolynesia.json",
        "Solomon Is.": "solomonis.json",
        "Tonga": "tonga.json",
        "Tuvalu": "tuvalu.json",
        "Vanuatu": "vanuatu.json",
        "Wallis and Futuna Is.": "wallisandfutunais.json",
        "Samoa": "samoa.json"
    },
    "Other": {
        "Antarctica": "antarctica.json",
        "Fr. S. Antarctic Lands": "frsantarcticlands.json",
        "Clipperton I.": "clippertoni.json",
        "Heard I. and McDonald Is.": "heardiandmcdonaldis.json",
        "Br. Indian Ocean Ter.": "brindianoceanter.json",
        "Maldives": "maldives.json",
        "Mauritius": "mauritius.json",
        "S. Geo. and S. Sandw. Is.": "sgeoandssandwis.json",
        "Saint Helena": "sainthelena.json",
        "Seychelles": "seychelles.json"
    }
}